name: build-test-deploy
# Changed 'on' to enable this workflow to be called from other workflows
on:
  workflow_call:
    inputs:
      node-version:
        description: "Node version"
        required: true
        type: string
      stage:
        description: "Stage"
        required: true
        type: string

jobs:
  initial:
    uses: hsandovaltides/shared_workflows/.github/workflows/test-build-deploy.yml@main
    with:
      node-version: ${{ inputs.node-version }}
      description: ${{ github.event.repository.name }}

  test:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      
      - run: npm install
      
      - name: Run npm test
        run: npm run test
        continue-on-error: true
      - name: Notify Failure
        if: ${{ failure() }}        
        uses: hsandovaltides/shared_workflows/.github/workflows/teams-notification.yml@main
        with:
          node-version: ${{ inputs.node-version }}
          description: "Test Failed"
        

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEV_REGION }}
      
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install modules
        run: npm install
      - name: Print Deploy
        run: ./node_modules/serverless/bin/serverless.js print --stage ${{ inputs.stage }}
      - name: Deploy App To Aws
        run: ./node_modules/serverless/bin/serverless.js deploy --stage ${{ inputs.stage }}
      
      - name: Notify Failure
        if: ${{ failure() }}        
        uses: hsandovaltides/shared_workflows/.github/workflows/teams-notification.yml@main
        with:
          node-version: ${{ inputs.node-version }}
          description: "Deploy Failed"

  
